// Code generated by MockGen. DO NOT EDIT.
// Source: cbupnvj/model (interfaces: TrainingHistoryService)

// Package mock is a generated GoMock package.
package mock

import (
	model "cbupnvj/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTrainingHistoryService is a mock of TrainingHistoryService interface.
type MockTrainingHistoryService struct {
	ctrl     *gomock.Controller
	recorder *MockTrainingHistoryServiceMockRecorder
}

// MockTrainingHistoryServiceMockRecorder is the mock recorder for MockTrainingHistoryService.
type MockTrainingHistoryServiceMockRecorder struct {
	mock *MockTrainingHistoryService
}

// NewMockTrainingHistoryService creates a new mock instance.
func NewMockTrainingHistoryService(ctrl *gomock.Controller) *MockTrainingHistoryService {
	mock := &MockTrainingHistoryService{ctrl: ctrl}
	mock.recorder = &MockTrainingHistoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrainingHistoryService) EXPECT() *MockTrainingHistoryServiceMockRecorder {
	return m.recorder
}

// CreateTrainingHistory mocks base method.
func (m *MockTrainingHistoryService) CreateTrainingHistory(arg0 context.Context, arg1 model.CreateTrainingHistoryRequest) (*model.TrainingHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTrainingHistory", arg0, arg1)
	ret0, _ := ret[0].(*model.TrainingHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTrainingHistory indicates an expected call of CreateTrainingHistory.
func (mr *MockTrainingHistoryServiceMockRecorder) CreateTrainingHistory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTrainingHistory", reflect.TypeOf((*MockTrainingHistoryService)(nil).CreateTrainingHistory), arg0, arg1)
}

// FindAllTrainingHistory mocks base method.
func (m *MockTrainingHistoryService) FindAllTrainingHistory(arg0 context.Context) ([]*model.TrainingHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllTrainingHistory", arg0)
	ret0, _ := ret[0].([]*model.TrainingHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllTrainingHistory indicates an expected call of FindAllTrainingHistory.
func (mr *MockTrainingHistoryServiceMockRecorder) FindAllTrainingHistory(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllTrainingHistory", reflect.TypeOf((*MockTrainingHistoryService)(nil).FindAllTrainingHistory), arg0)
}
