// Code generated by MockGen. DO NOT EDIT.
// Source: cbupnvj/model (interfaces: RuleRepository)

// Package mock is a generated GoMock package.
package mock

import (
	model "cbupnvj/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRuleRepository is a mock of RuleRepository interface.
type MockRuleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRuleRepositoryMockRecorder
}

// MockRuleRepositoryMockRecorder is the mock recorder for MockRuleRepository.
type MockRuleRepositoryMockRecorder struct {
	mock *MockRuleRepository
}

// NewMockRuleRepository creates a new mock instance.
func NewMockRuleRepository(ctrl *gomock.Controller) *MockRuleRepository {
	mock := &MockRuleRepository{ctrl: ctrl}
	mock.recorder = &MockRuleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleRepository) EXPECT() *MockRuleRepositoryMockRecorder {
	return m.recorder
}

// CountAll mocks base method.
func (m *MockRuleRepository) CountAll(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAll", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAll indicates an expected call of CountAll.
func (mr *MockRuleRepositoryMockRecorder) CountAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAll", reflect.TypeOf((*MockRuleRepository)(nil).CountAll), arg0)
}

// Create mocks base method.
func (m *MockRuleRepository) Create(arg0 context.Context, arg1 *model.Rule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRuleRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRuleRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockRuleRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRuleRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRuleRepository)(nil).Delete), arg0, arg1)
}

// FindAll mocks base method.
func (m *MockRuleRepository) FindAll(arg0 context.Context, arg1 string) ([]*model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0, arg1)
	ret0, _ := ret[0].([]*model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRuleRepositoryMockRecorder) FindAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRuleRepository)(nil).FindAll), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockRuleRepository) FindByID(arg0 context.Context, arg1 string) (*model.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*model.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRuleRepositoryMockRecorder) FindByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRuleRepository)(nil).FindByID), arg0, arg1)
}

// Update mocks base method.
func (m *MockRuleRepository) Update(arg0 context.Context, arg1 string, arg2 *model.Rule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRuleRepositoryMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRuleRepository)(nil).Update), arg0, arg1, arg2)
}
