// Code generated by MockGen. DO NOT EDIT.
// Source: cbupnvj/model (interfaces: MajorRepository)

// Package mock is a generated GoMock package.
package mock

import (
	model "cbupnvj/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMajorRepository is a mock of MajorRepository interface.
type MockMajorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMajorRepositoryMockRecorder
}

// MockMajorRepositoryMockRecorder is the mock recorder for MockMajorRepository.
type MockMajorRepositoryMockRecorder struct {
	mock *MockMajorRepository
}

// NewMockMajorRepository creates a new mock instance.
func NewMockMajorRepository(ctrl *gomock.Controller) *MockMajorRepository {
	mock := &MockMajorRepository{ctrl: ctrl}
	mock.recorder = &MockMajorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMajorRepository) EXPECT() *MockMajorRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockMajorRepository) FindAll(arg0 context.Context) ([]*model.Major, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].([]*model.Major)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockMajorRepositoryMockRecorder) FindAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockMajorRepository)(nil).FindAll), arg0)
}

// FindByID mocks base method.
func (m *MockMajorRepository) FindByID(arg0 context.Context, arg1 string) (*model.Major, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*model.Major)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockMajorRepositoryMockRecorder) FindByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockMajorRepository)(nil).FindByID), arg0, arg1)
}
