// Code generated by MockGen. DO NOT EDIT.
// Source: cbupnvj/model (interfaces: ReqBodyRepository)

// Package mock is a generated GoMock package.
package mock

import (
	model "cbupnvj/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockReqBodyRepository is a mock of ReqBodyRepository interface.
type MockReqBodyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReqBodyRepositoryMockRecorder
}

// MockReqBodyRepositoryMockRecorder is the mock recorder for MockReqBodyRepository.
type MockReqBodyRepositoryMockRecorder struct {
	mock *MockReqBodyRepository
}

// NewMockReqBodyRepository creates a new mock instance.
func NewMockReqBodyRepository(ctrl *gomock.Controller) *MockReqBodyRepository {
	mock := &MockReqBodyRepository{ctrl: ctrl}
	mock.recorder = &MockReqBodyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReqBodyRepository) EXPECT() *MockReqBodyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReqBodyRepository) Create(arg0 context.Context, arg1 *gorm.DB, arg2 *model.ReqBody) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReqBodyRepositoryMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReqBodyRepository)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockReqBodyRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReqBodyRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReqBodyRepository)(nil).Delete), arg0, arg1)
}

// FindAll mocks base method.
func (m *MockReqBodyRepository) FindAll(arg0 context.Context, arg1 string, arg2 model.HttpMethod) ([]*model.ReqBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*model.ReqBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockReqBodyRepositoryMockRecorder) FindAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockReqBodyRepository)(nil).FindAll), arg0, arg1, arg2)
}

// FindByID mocks base method.
func (m *MockReqBodyRepository) FindByID(arg0 context.Context, arg1 string) (*model.ReqBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*model.ReqBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockReqBodyRepositoryMockRecorder) FindByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockReqBodyRepository)(nil).FindByID), arg0, arg1)
}

// Update mocks base method.
func (m *MockReqBodyRepository) Update(arg0 context.Context, arg1 string, arg2 *model.ReqBody) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockReqBodyRepositoryMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockReqBodyRepository)(nil).Update), arg0, arg1, arg2)
}
