// Code generated by MockGen. DO NOT EDIT.
// Source: cbupnvj/model (interfaces: StoryRepository)

// Package mock is a generated GoMock package.
package mock

import (
	model "cbupnvj/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockStoryRepository is a mock of StoryRepository interface.
type MockStoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStoryRepositoryMockRecorder
}

// MockStoryRepositoryMockRecorder is the mock recorder for MockStoryRepository.
type MockStoryRepositoryMockRecorder struct {
	mock *MockStoryRepository
}

// NewMockStoryRepository creates a new mock instance.
func NewMockStoryRepository(ctrl *gomock.Controller) *MockStoryRepository {
	mock := &MockStoryRepository{ctrl: ctrl}
	mock.recorder = &MockStoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoryRepository) EXPECT() *MockStoryRepositoryMockRecorder {
	return m.recorder
}

// CountAll mocks base method.
func (m *MockStoryRepository) CountAll(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAll", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAll indicates an expected call of CountAll.
func (mr *MockStoryRepositoryMockRecorder) CountAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAll", reflect.TypeOf((*MockStoryRepository)(nil).CountAll), arg0)
}

// Create mocks base method.
func (m *MockStoryRepository) Create(arg0 context.Context, arg1 *model.Story) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStoryRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStoryRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockStoryRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStoryRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStoryRepository)(nil).Delete), arg0, arg1)
}

// DeleteWithContext mocks base method.
func (m *MockStoryRepository) DeleteWithContext(arg0 context.Context, arg1 *gorm.DB, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithContext", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWithContext indicates an expected call of DeleteWithContext.
func (mr *MockStoryRepositoryMockRecorder) DeleteWithContext(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithContext", reflect.TypeOf((*MockStoryRepository)(nil).DeleteWithContext), arg0, arg1, arg2)
}

// FindAll mocks base method.
func (m *MockStoryRepository) FindAll(arg0 context.Context, arg1 string) ([]*model.Story, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0, arg1)
	ret0, _ := ret[0].([]*model.Story)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockStoryRepositoryMockRecorder) FindAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockStoryRepository)(nil).FindAll), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockStoryRepository) FindByID(arg0 context.Context, arg1 string) (*model.Story, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*model.Story)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockStoryRepositoryMockRecorder) FindByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockStoryRepository)(nil).FindByID), arg0, arg1)
}

// Update mocks base method.
func (m *MockStoryRepository) Update(arg0 context.Context, arg1 string, arg2 *model.Story) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStoryRepositoryMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStoryRepository)(nil).Update), arg0, arg1, arg2)
}
