// Code generated by MockGen. DO NOT EDIT.
// Source: cbupnvj/model (interfaces: UtteranceRepository)

// Package mock is a generated GoMock package.
package mock

import (
	model "cbupnvj/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUtteranceRepository is a mock of UtteranceRepository interface.
type MockUtteranceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUtteranceRepositoryMockRecorder
}

// MockUtteranceRepositoryMockRecorder is the mock recorder for MockUtteranceRepository.
type MockUtteranceRepositoryMockRecorder struct {
	mock *MockUtteranceRepository
}

// NewMockUtteranceRepository creates a new mock instance.
func NewMockUtteranceRepository(ctrl *gomock.Controller) *MockUtteranceRepository {
	mock := &MockUtteranceRepository{ctrl: ctrl}
	mock.recorder = &MockUtteranceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUtteranceRepository) EXPECT() *MockUtteranceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUtteranceRepository) Create(arg0 context.Context, arg1 *model.Utterance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUtteranceRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUtteranceRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockUtteranceRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUtteranceRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUtteranceRepository)(nil).Delete), arg0, arg1)
}

// FindAll mocks base method.
func (m *MockUtteranceRepository) FindAll(arg0 context.Context, arg1 string) ([]*model.Utterance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0, arg1)
	ret0, _ := ret[0].([]*model.Utterance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockUtteranceRepositoryMockRecorder) FindAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockUtteranceRepository)(nil).FindAll), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockUtteranceRepository) FindByID(arg0 context.Context, arg1 string) (*model.Utterance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*model.Utterance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUtteranceRepositoryMockRecorder) FindByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUtteranceRepository)(nil).FindByID), arg0, arg1)
}

// Update mocks base method.
func (m *MockUtteranceRepository) Update(arg0 context.Context, arg1 string, arg2 *model.Utterance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUtteranceRepositoryMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUtteranceRepository)(nil).Update), arg0, arg1, arg2)
}
